
```{r}
rm(list=ls())

#### Check packages installed ####
checkpackage<-function(U){
  if((U %in% rownames(installed.packages()))==F){
    install.packages(U)
    library(U, character.only = TRUE)
  }else{
    library(U, character.only = TRUE)
  }
}
packagelist<-list("lattice", "Rcpp", "MASS","methods", "zoo", "stats","utils","grDevices",
                  "graphics","RcppArmadillo", "RcppEigen", "R.matlab")
lapply(packagelist,checkpackage)

#### Source Functions ####
source("mainfunctionsinR.R") # Main Functions in R 
Sys.setenv("PKG_CXXFLAGS"="-std=c++11")
sourceCpp('mainfunctionsinC.cpp') # Main Functions in C
sourceCpp('auxftc.cpp') # Auxiliary Functions
```


```{r}
load(file="TrueZerosS5.RData")
load(file="YYS5.RData")
Nsim <- 500
k=10; p=12; n=200
Sim5Lag <- matrix(NA, ncol=11, nrow=Nsim)
colnames(Sim5Lag) <- c("HLagC", "HLagOO", "HLagElem", "Lasso", "LagLasso", "LS AIC", "LS BIC", "Mean", "RW", "BGR", "GLP")

# Methods that do not perform lag selection performance
TrueZeros <- TrueZerosS5
Sim5Lag[,8] <- (sum(abs(TrueZeros-matrix(0, ncol=k, nrow=k))))/sum(abs(TrueZeros))
Sim5Lag[,9] <- (sum(abs(TrueZeros-diag(1,k))))/sum(abs(TrueZeros))
Sim5Lag[,10:11] <- (sum(abs(TrueZeros-matrix(12, ncol=k, nrow=k))))/sum(abs(TrueZeros))

for(r in 1:Nsim){
  r <- 1
  # Data
  Y <- YYS5[[r]]
  
  A <- constructModel(Y, p=12, "Basic", gran=c(5000,10),verbose=F,ONESE=TRUE,RVAR=TRUE,
                      lagselect = TRUE,tol=1e-6, T1=floor(0.67*n), T2=n-2)
  
  # Lasso
  resH <- cv.BigVAR(A)
  Sim5Lag[r, 4] <- resH@SR[length(resH@SR)]

  # AIC and BIC 
  AICp <- resH@AICpvec[1]
  Sim5Lag[r, 6] <- (sum(abs(TrueZeros-matrix(AICp, ncol=k, nrow=k))))/sum(abs(TrueZeros))
  BICp <- resH@BICpvec[1]
  Sim5Lag[r, 7] <- (sum(abs(TrueZeros-matrix(BICp, ncol=k, nrow=k))))/sum(abs(TrueZeros))
  
  # Componentwise
  A@Structure <- "HVARC"
  resH <- cv.BigVAR(A)
  Sim5Lag[r, 1] <- resH@SR[length(resH@SR)]
  
  # Own-other
  A@Structure <- "HVAROO"
  resH <- cv.BigVAR(A)
  Sim5Lag[r, 2] <- resH@SR[length(resH@SR)]
  
  # Elementwise
  A@Structure <- "HVARELEM"
  resH <- cv.BigVAR(A)
  Sim5Lag[r, 3] <- resH@SR[length(resH@SR)]
  
  # Lag-Weighted Lasso
  A@Structure <- "Tapered"
  resH <- cv.BigVAR(A)
  Sim5Lag[r, 5] <- resH@SR[length(resH@SR)]


}
apply(Sim5Lag, 2, mean)
```
```{r}
resH@SR
```

